### ISSUE TITLE
plugin dies in php storm 10.

### ISSUE THREAD

**Issue by dospuntocero** [raket/idea-silverstripe#71]
details:

```java

com.intellij.psi.templateLanguages.TemplateDataLanguageMappings.getMapping(Lcom/intellij/openapi/vfs/VirtualFile;)Lcom/intellij/lang/Language;
java.lang.NoSuchMethodError: com.intellij.psi.templateLanguages.TemplateDataLanguageMappings.getMapping(Lcom/intellij/openapi/vfs/VirtualFile;)Lcom/intellij/lang/Language;
	at com.raket.silverstripe.file.SilverStripeFileViewProvider.getTemplateDataLanguage(SilverStripeFileViewProvider.java:39)
	at com.raket.silverstripe.file.SilverStripeFileViewProvider.<init>(SilverStripeFileViewProvider.java:35)
	at com.raket.silverstripe.file.SilverStripeFileViewProviderFactory.createFileViewProvider(SilverStripeFileViewProviderFactory.java:13)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.createFileViewProvider(FileManagerImpl.java:292)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:226)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:409)
	at com.intellij.psi.impl.PsiDocumentManagerBase.c(PsiDocumentManagerBase.java:164)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getPsiFile(PsiDocumentManagerBase.java:118)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.getPsiFile(PsiDocumentManagerImpl.java:94)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo$1.run(DocumentFoldingInfo.java:294)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:951)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.readExternal(DocumentFoldingInfo.java:284)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.readFoldingState(CodeFoldingManagerImpl.java:382)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.readState(PsiAwareTextEditorProvider.java:107)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.<init>(HistoryEntry.java:79)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:872)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:831)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$ConfigTreeReader.process(EditorsSplitters.java:822)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.openFiles(EditorsSplitters.java:244)
	at com.intellij.openapi.fileEditor.impl.OpenFilesActivity.runActivity(OpenFilesActivity.java:35)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:147)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:342)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:152)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$5.run(ProjectManagerImpl.java:386)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:634)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)



```

**Comment by rimu** [comment]
I got the same error on PHPStorm 9.0.2. Downgrading to version 0.9.1.2 of this plugin solved it.
